21 user profile closes #21
blueteamcpu/learn-together pull request #40
Opened 2019-09-13 03:30 UTC by CB6670

2019-09-13 05:28 UTC, justin-cook-developer requested changes

2019-09-13 05:28 UTC, justin-cook-developer commented on client/actions/user.js
> +import { log } from "util";
What is this import?

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/App/AppDumb.js
> +          <Route path = "/profile" component = {UserProfile} />
Maybe wrap this in a protected Route? Like LoggedInOnly?

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/UserProfile/UserProfile.js
> +  if (!state.authentication.user){
User will always be an object. See auth reducer initial state. Maybe check for user.id?

2019-09-13 05:28 UTC, justin-cook-developer commented on client/actions/user.js
> +      console.log('updated user: ', updatedUser);
Remove this log.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/actions/user.js
> +export const _updateUser = user => ({
This feels redundant with got_user in /actions/auth. I would use the same action creator.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/actions/user.js
> +export const _updateUser = user => ({
Remove the type as well.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/App/AppDumb.js
> +import CreateEventForm from '../CreateEventForm/CreateEventFormDumb'
Do you mean to render CreateEvent instead of Create...Dumb?

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/UserProfile/UserProfile.js
> +  getUser() {
This should get removed b/c it is on app already. You likely have a no-rerender issue. I can help you fix that, but don't get the user twice.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/UserProfile/UserProfileDumb.js
> +    async componentDidMount(){
You should be able to get rid of this. You can use the key prop to force a rerender on a form when props change. Set the forms initial state from props and provide default props as well. I can help with this.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/UserProfile/UserProfileDumb.js
> +        await this.props.getUser();
This needs to go as well. Too many fetches of user.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/components/UserProfile/UserProfileDumb.js
> +          this.props.updateUser(firstName, lastName, username, email, zipcode);
I don't think you should update password and user info. I think it should be one or the other. If you are editing password, you can't edit info, and vice versa. Separate forms would make this easy.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/reducers/authentication.js
> +import {
Redundant to GOT_USER. I think you should use GOT_USER.

2019-09-13 05:28 UTC, justin-cook-developer commented on client/reducers/authentication.js
> +    case UPDATEUSER: {
Redundant to GOT_USER

2019-09-13 05:28 UTC, justin-cook-developer commented on server/apiRoutes/user/user.js
> +        const newUser = await User.update({
User req.user.update so beforeUpdate hook will trigger. It is good for string formatting.

2019-09-13 05:28 UTC, justin-cook-developer commented on server/apiRoutes/user/user.js
> +        if (validation && req.user.id === req.session.userId){
req.user.id will always equal req.session.id

2019-09-13 05:28 UTC, justin-cook-developer commented on server/app/index.js
> +app.use('/user', require('../apiRoutes/user/user'));
Move to /api/index.js

2019-09-13 21:04 UTC, CB6670 commented on client/actions/user.js
> +import { log } from "util";
This is something that my pc keeps doing and I'm kinda perplexed as to why. I'll clean this up

2019-09-13 21:06 UTC, CB6670 commented on client/components/UserProfile/UserProfile.js
> +  getUser() {
Ok, I'll get rid of that.

2019-09-13 21:07 UTC, CB6670 commented on client/components/App/AppDumb.js
> +import CreateEventForm from '../CreateEventForm/CreateEventFormDumb'
That's some code that I pulled in from the master branch. I'll change it and push it back up.

2019-09-13 21:08 UTC, CB6670 commented on client/components/UserProfile/UserProfileDumb.js
> +    async componentDidMount(){
Ok, sounds good. I'll clean these up and have them ready to change for when you have time to look at it with me.

2019-09-13 21:09 UTC, CB6670 commented on client/components/UserProfile/UserProfileDumb.js
> +          this.props.updateUser(firstName, lastName, username, email, zipcode);
Ok. I'll change the functionality of the form I have up currently then.

2019-09-13 21:11 UTC, CB6670 commented on server/apiRoutes/user/user.js
> +        if (validation && req.user.id === req.session.userId){
Ok, what would be the best way to check to make sure that the correct user is updating this user's password then?

2019-09-15 02:56 UTC, octokatherine approved these changes

2019-09-15 02:59 UTC, justin-cook-developer approved these changes

2019-09-15 02:59 UTC, merged