Group detail user aware
blueteamcpu/learn-together pull request #62
Opened 2019-09-20 04:30 UTC by nicknapoli82

Adding client application user awareness for group context. 
It knows if the user is logged in or not, and allows a user to join a group or leave a group.

NOT COMPLETE. Just helper code to allow everyone else work on their own slice of the application

2019-09-20 05:52 UTC, justin-cook-developer commented on client/components/Group/GroupDetail.js
> +      const result = axios.post('/api/groups/addself', {groupId: match.params.groupId});
I think you need to await here.

2019-09-20 05:52 UTC, justin-cook-developer commented on client/components/Group/GroupDetail.js
> +      const result = axios.delete('/api/groups/removeself', {data: {groupId: match.params.groupId}});
await?

2019-09-20 06:01 UTC, justin-cook-developer requested changes

2019-09-20 06:01 UTC, justin-cook-developer commented on client/components/Group/GroupDetail.js
> +    if(this.props.members.length && this.props.user.id !== undefined) {
Does this put you in an infinite loop? I think you might want to add a conditional to check if isMember is already true. didUpdate has the signature (prevProps, prevState)

2019-09-21 01:20 UTC, nicknapoli82 commented
Alright. I made some fair changes to how the data works through this slice of the app now. 
Moved some of the Component state out of the GroupDetail component and into the groups redux store. Pretty much solves the problems I created earlier.

Let me know if you see anything that looks wrong. 

Still not done, but this is a better working model now IMO

2019-09-21 16:25 UTC, justin-cook-developer approved these changes

2019-09-21 16:25 UTC, merged